### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nguyenhothanhtam0709** [cyanogilvie/Tcl.js#5]
I have a question about the license of this project. Can I fork this project or port it to typescript?

**Comment by cyanogilvie** [comment]
Sure.  The license is the same variant of the BSD that the Tcl core uses (in the LICENSE file at the root of the repo).  It basically allows you do to just about anything with it.

**Comment by nguyenhothanhtam0709** [comment]
@cyanogilvie , thanks for your response
